---
#
# base provisioning for a server
#
- name: Ensure the locale exists
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: set as default locale
  command: localectl set-locale LANG=en_GB.UTF-8 LC_CTYPE=en_GB.UTF-8 LANGUAGE=en_GB:en

- name: set timezone to Europe/London
  timezone:
    name: Europe/London
  register: timezone
  tags:
    - timezone

- name: restart cron
  service:
    name: cron
    state: restarted
  when: timezone.changed
  tags:
    - timezone

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
  notify: restart ssh

- import_tasks: firewall.yml
- import_tasks: unattended-upgrades.yml
- import_tasks: upgrade.yml

# precaution before running the rest
# - only real issue is with CRON and possibly locale change
- name: Unconditionally reboot the machine with all defaults
  reboot: