Documentation:
 Enabled: false
MethodDefParentheses:
 Enabled: false
Style/UnneededPercentQ:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*

