scss_files: 'app/assets/stylesheets/**/*.css.scss'

exclude:
  - 'app/assets/stylesheets/module.scss'
  - 'app/assets/stylesheets/normalize.scss'

linters:
  Comment:
    enabled: false

  ColorKeyword:
    enabled: false

  QualifyingElement:
    enabled: false

  SingleLinePerSelector:
     enabled: false

  PlaceholderInExtend:
     enabled: false

  # Linters we want to enable
  VendorPrefixes:
    enabled: false

