scss_files: 'app/assets/stylesheets/**/*.css.scss'

exclude:
  - 'app/assets/stylesheets/generic.normalize.css'
  - 'tmp/rubycritic/assets/stylesheets/*.css'

linters:
  Comment:
    enabled: false

  ColorKeyword:
    enabled: false

  # Worth Enabling

  SingleLinePerSelector:
    enabled: false

  QualifyingElement:
    enabled: false

  PlaceholderInExtend:
     enabled: false
