language: ruby

sudo: false

rvm:
  - "2.1.2"

env:
  - DB=postgresql

addons:
  postgresql: 9.3

services:
  - elasticsearch

before_script:
  - bundle exec rake db:create RAILS_ENV=test

script:
  - bundle exec rake db:migrate
  - bundle exec xvfb-run rspec
  - bundle exec rake db:seed RAILS_ENV=test

notifications:
  email: true
  slack: bcs-io:j4u422myY0CcryFquMCAOi45
  webhooks:
    on_success: change
    on_failure: always

