language: ruby
rvm:
  - "2.1.2"
env:
  - DB=postgresql

addons:
  postgresql: 9.3

services:
  - elasticsearch

script:
  - bundle exec rake db:migrate
  - bundle exec xvfb-run rspec
before_script:
  - bundle exec rake db:create RAILS_ENV=test

notifications:
  email: true
  slack: bcs-io:j4u422myY0CcryFquMCAOi45
  webhooks:
    on_success: change
    on_failure: always
