---
domains:
  - local.fl-adams.uk

database: letting_production
database_port: 5555

# AWS
#  - aws data is spread out over three different files
#  - secret.yml - for the secret infor
#    - aws_access_key_id
#    - aws_secret_access_key
#  - group_vars/all.yml - for the shared
#    - aws_region - shared regions
#  - host_vars/host-name - host specific variables
#    - aws_bucket_name

# AWS
aws_bucket_name: local.fl-adams.uk

# user message
rack_dev_mark_env: LIVE 