---
- import_role:
    name: dokku_bot.ansible_dokku
  vars:
    dokku_skip_key_file: 'true'
    dokku_version: 0.17.7
    dokku_vhost_enable: 'true'
    dokku_web_config: 'false'
    herokuish_version: 0.5.2
    plugn_version: 0.3.2
    sshcommand_version: 0.8.0
    dokku_users:
      - name: richard
        username: richard
        ssh_key: "{{ lookup('file', controller_key) }}"

- name: apps:create {{ application }}
  dokku_app:
    app: "{{ application }}"
    state: present
  tags:
    - dokku

- name: domains:add {{ application }} {{ domain }}
  dokku_domains:
    app: "{{ application }}"
    domains:
      - "{{ domain }}"
    state: present
  tags:
    - dokku

- name: config:set {{ application }} RAILS_MASTER_KEY=XXXX
  dokku_config:
    app: "{{ application }}"
    config:
      RAILS_MASTER_KEY: "{{ lookup('file', rails_master_key )}}"
  tags:
    - dokku
    - doit

- name: config:set {{ application }} banner mark
  dokku_config:
    app: "{{ application }}"
    config:
      RACK_DEV_MARK_ENV: "{{ rack_dev_mark_env }}"
  # when: rack_dev_mark_env is defined

- name: Creates nightly hiding of monotonous accounts
  cron:
    name: "Rails Account.hide_monotonous_account_details (nightly)"
    cron_file: "account_hide_monotonous_account_details"
    minute: "23"
    hour: "4"
    user: "root"
    #                                                                                                              redirect stdout and std error to null
    job: /usr/bin/dokku --rm run letting "bundle exec rake RAILS_ENV=production 'hide_monotonous_account_details'" >/dev/null 2>&1
  tags:
    - dokku
    - cronjobs

- import_tasks: elasticsearch.yml
- import_tasks: database.yml
- import_tasks: elasticsearch_sync.yml
- import_tasks: ssl.yml
