---
- import_role:
    name: dokku_bot.ansible_dokku
  vars:
    dokku_plugins:
      - name: letsencrypt
        url: https://github.com/dokku/dokku-letsencrypt.git

- name: config:set  {{ application }} DOKKU_LETSENCRYPT_EMAIL=${DOKKU_LETSENCRYPT_EMAIL}
  dokku_config:
    app: "{{ application }}"
    config:
      DOKKU_LETSENCRYPT_EMAIL: "{{ ops_email }}"
  tags:
    - dokku
    - ssl

#
# If this fails have you pushed the code?
#
#
- name: website {{ application }}
  uri:
    url: http://{{ item }}
  loop: "{{ domains }}"
  tags:
    - dokku
    - ssl
#
# ansible has import_role apply tags but could not get it to work
#
- name: all access
  ufw:
    rule: allow
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'
  tags:
    - dokku
    - ssl

- name: letsencrypt:auto-rewnew {{ application }}
  command: dokku letsencrypt:auto-renew {{ application }}
  when:
    - "'encrypt' in group_names"
  tags:
    - dokku
    - ssl

- name: delete all access
  ufw:
    rule: allow
    to_port: "{{ item }}"
    proto: tcp
    delete: yes
  loop:
    - '80'
    - '443'
  tags:
    - dokku
    - ssl