# Add application configuration variables here, as shown below.
#
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

SECRET_KEY_BASE: 'INSERT HERE OR "rake secret" to generate'

# Database.yml settings
database: insert database name
username: insert username name
password: insert database password