# PostgreSQL. Versions 8.2 and up are supported.
#
development:
  adapter: postgresql
  encoding: unicode
  database: letting_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: letting_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ADD DATABASE NAME HERE
  pool: 5
  username: ADD USERNAME HERE
  password: ADD PASSWORD HERE
