# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# You have to expose this value to travis - you can encrypt it (see link).
# http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
# I prefer to underline that this isn't secure - as all encyptions are overcome.
test:
  secret_key_base: 9f464bfe1f202b3f642f0a5d30a04108410adf57b2d469e84a0c2d293bde53741768d5138d1cca4d7dd2ebbce2466d700d6ec533e2e4061a99b13489e51aabc7

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Hey, I didn't make them only settable by environment
