# Configurations required to run the application
#
# Copy the file to secrets.yml
#   - add different secret_key_base to staging, internet and production
#   - rake secret
#     - 3 times!
#
#
# Must be available in production all the application will fail
#   - see capistrano secrets task
# NEVER INCLUDE IN GITHUB
# RESTART your server after modifying


development:
  secret_key_base: 3d8bfd6af595a93cab114d48703124e0b001d56dc88be40368098165e1b86cf817d7d06cd593ecd8f00954bb3aa77eccdbfa26687fcb6c9bebcf45501a00633e

# You have to expose this value to travis - you can encrypt it (see link).
# http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
# I prefer to underline that this isn't secure - as all encyptions are overcome.
test:
  secret_key_base: 9f464bfe1f202b3f642f0a5d30a04108410adf57b2d469e84a0c2d293bde53741768d5138d1cca4d7dd2ebbce2466d700d6ec533e2e4061a99b13489e51aabc7

staging:
  secret_key_base: RUN_RAKE_SECRETS_AND_PASTE_OVER_THIS

internet:
  secret_key_base: RUN_RAKE_SECRETS_AND_PASTE_OVER_THIS

production:
  secret_key_base: RUN_RAKE_SECRETS_AND_PASTE_OVER_THIS
