---
#
# ansible-playbook playbook.yml --limit appservers -vvv
#
- import_playbook: bootstrap.yml

- hosts: all
  remote_user: deployer
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - base
    - dokku