---
#
# ansible-playbook playbook.yml --limit appservers -vvv
#
- hosts: all
  remote_user: deployer
  become: yes
  vars_files:
    - vars/secrets.yml
  roles:
    - base

  handlers:
     - name: restart ssh
       service: name=ssh state=restarted