#
# Gemfile
#
# Keeping a Gemfile up to date and especially updated Gems with security issues
# is an important maintenance task.
#
# 1) Which Gems are out of date?
# 2) Update a Gem
# 3) Gemfile.lock
# 4) Versioning
# 5) Importance of a Gem to the Application
# 6) Resetting Gems back to the original version
# 7) Breaking Gem List
#
#
# 1) Which Gems are out of date?
#
# bundle outdated  or use https://gemnasium.com/BCS-io/letting
#
#
# 2) Update a Gem
#
#  Update a single Gem using bundle update < gem name >
#    - example of pg: bundle update gp
#
# If a gem has not changed check what restrictions the Gemfile specifies
# Taking pg as an example again. We can update to 0.18.1, 0.18.2, 0.18.3
# but not update to 0.19.1. To update to 0.19.1 you need to change the Gem
# statement in this file and then run bundle update as above.
#
# gem 'pg', '~>0.18.0'     =>      gem 'pg', '~>0.19.0'
#
# After updating a gem run rake though and if it passes before pushing up.
#
#
# 3) Gemfile.lock
#
# You should never change Gemfile.lock directly. By changing Gemfile and
# running bundle commands you change Gemfile.lock indirectly.
#
#
# 4) Versioning
#
# Most Gems follow Semantic Versioning:  http://semver.org/
#
# Risk of causing a problem:
# Low: 0.18.0 => 0.18.X        - bug fixes
# Low-Medium: 0.18.0 => 0.19.0 - New functionality but should not break old
#                                functionality.
# High:       0.18 = > 1.0.0   - Breaking changes with past code.
#
#
# 5) Importance of a Gem to the Application
#
# Gems which are within development will not affect the production application:
#
#  group :development do
#    gem 'better_errors', '~> 2.1.0'
#  end
#
# Gems without a block will affect the production application and you should be
# more careful with the update.
#
#
# 6) Resetting Gems back to the original version
#
# If you need to return your Gems to original version.
# a) git checkout .
# b) bundle install
#

#
# GEMS THAT BREAK THE BUILD
#
# A list of Gems that if updated will break the application.
#
# Gem                     Using      Last tested   Gem Bug
# rake                   10.1.0           11.2.2         ?
#
#
source 'https://rubygems.org'
ruby '~> 2.5.0'

#
# Production
#
gem 'autoprefixer-rails', '~> 9.4.0'
gem 'bcrypt', '~> 3.1.12'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'coffee-rails', '~> 4.2.0'
gem 'elasticsearch', '~> 6.0.0'
gem 'elasticsearch-model', '~> 6.0.0'
gem 'elasticsearch-rails', '~> 6.0.0'
gem 'equalizer'
gem 'font-awesome-rails'
gem 'inline_svg', '~> 1.6.0'
gem 'jbuilder', '~> 2.7.0'
gem 'jquery-rails', '~> 4.3.0'

# BREAKING GEM
# 5.0.3 - causes CapybaraHelper to fail
gem 'jquery-ui-rails', '6.0.1'

# Kaminari before elasticsearch
gem 'kaminari', '~> 1.2.0'
gem 'lograge'
gem 'nokogiri', '>= 1.8.2' # to avoid vulnerability
gem 'pg', '~>0.20.0' # rails 5 required to use pg 1.0+
gem 'puma', '~> 4.3'
gem 'rack-dev-mark', '~> 0.7.0' # corner banner on staging environment
gem 'rails', '~> 5.2.4'
gem 'rails-env-favicon'

gem 'rake', '~> 12.3'
gem 'redis', '~> 4.0'
gem 'sass-rails', '~> 5.0.0'
gem 'seedbank'
gem 'sprockets', '~>3.7.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '~> 2.7.0'

#
# Development only
#
group :development do
  gem 'better_errors', '~> 2.5.0'
  gem 'binding_of_caller', '~> 0.8.0'
  gem 'brakeman', '~>4.3.0', require: false
  gem 'bullet', '~>5.9.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rails-erd'
  gem 'rails_best_practices', '~>1.15.0'
  gem 'require_all', '~> 1.0' # 2.0 seems to break rails_best_practice
  # Remove to avoid vulnerability
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubycritic', require: false
  gem 'scss_lint', '~> 0.57.0', require: false
  gem 'traceroute'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '>= 3.3.0'
end

#
# Development and testing
#
group :development, :test do
  #
  # BREAKING GEM
  # Throwing exceptions when it hits breakpoints
  #
  gem 'bundler-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # 0.1.1 seems to introduce errors - Use this gem occasionally to weed out
  # performance errors with tests
  # gem 'capybara-slow_finder_errors', '0.1.0'
  gem 'meta_request'
  gem 'pry-rails', '~>0.3.0'
  gem 'pry-stack_explorer', '~>0.4.9.0'
  gem 'rack-mini-profiler', '~>1.0.0'
  gem 'rb-readline'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'table_print'
  gem 'zonebie', '~> 0.6.0'
end

#
# Testing
#
group :test do
  gem 'capybara', '~> 2.15.0'
  gem 'capybara-screenshot', '~> 1.0.0'

  # Create e.s. test node
  gem 'elasticsearch-extensions'
  gem 'rspec-rails', '~> 3.8.0'
  gem 'selenium-webdriver', '~>3.0'
  gem 'stackprof', '>= 0.2.9', require: false
  gem 'test-prof'
  gem 'timecop', '~>0.8.0'
  gem 'webdrivers', '~> 3.0'
end
